// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToe.Data.Contextes;

#nullable disable

namespace TicTacToe.Data.Migrations
{
    [DbContext(typeof(GameRecordContext))]
    [Migration("20221221145100_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("TicTacToe.Data.Models.GameRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerOType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerX")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerXType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinningLine")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
